import { ArrowRight, BarChart3, Bot, Brain, Cloud, Code2, Sparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";

const services = [
  { icon: Brain, title: "AI Strategy & Consulting", eyebrow: "AI Advisory", description: "Define a practical AI roadmap, assess readiness and prioritize opportunities with measurable business value.", accent: "from-blue-600 to-indigo-700" },
  { icon: Sparkles, title: "Generative AI Solutions", eyebrow: "AI Applications", description: "Build trusted LLM, RAG, assistant and copilot experiences grounded in your organization’s knowledge.", accent: "from-violet-600 to-indigo-700" },
  { icon: Bot, title: "AI Agents & Automation", eyebrow: "Intelligent Workflows", description: "Automate repetitive processes with human-aware agents, integrations and approval-based workflows.", accent: "from-cyan-600 to-blue-700" },
  { icon: BarChart3, title: "Data Analytics & BI", eyebrow: "Data Intelligence", description: "Turn fragmented enterprise data into governed analytics, dashboards and actionable operating insight.", accent: "from-sky-600 to-cyan-700" },
  { icon: Code2, title: "Web & Application Development", eyebrow: "Product Engineering", description: "Create responsive business platforms, customer portals and scalable software built for real users.", accent: "from-indigo-600 to-blue-800" },
  { icon: Cloud, title: "Cloud & DevOps", eyebrow: "Cloud Foundations", description: "Deploy reliable cloud infrastructure, delivery pipelines and secure environments that scale with demand.", accent: "from-blue-700 to-slate-800" },
];

export default function Services() {
  const navigate = useNavigate();
  return <section className="relative overflow-hidden bg-[#f4f7fc] py-20 md:py-28"><div className="absolute inset-x-0 top-0 h-72 bg-[radial-gradient(circle_at_50%_0%,rgba(37,99,235,.12),transparent_65%)]"/><div className="relative mx-auto max-w-[1320px] px-6"><div className="flex flex-col items-center text-center"><p className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-white px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-[#1559bd]"><Sparkles size={14}/> Our capabilities</p><h2 className="mt-6 max-w-3xl text-4xl font-bold leading-tight text-[#071B3B] md:text-6xl">Digital solutions that turn complex work into progress.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">From strategy through delivery, ARINSA AI MINDS combines AI, data, software and cloud expertise to build technology people can use.</p></div><div className="mt-14 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => { const Icon = service.icon; return <article key={service.title} className="group relative overflow-hidden rounded-3xl border border-slate-200 bg-white p-7 shadow-[0_12px_35px_rgba(7,27,59,.06)] transition duration-300 hover:-translate-y-2 hover:border-blue-300 hover:shadow-[0_24px_55px_rgba(25,89,237,.16)]"><div className={`absolute inset-x-0 top-0 h-1 bg-gradient-to-r ${service.accent}`}/><div className="flex items-start justify-between gap-5"><span className={`flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br ${service.accent} text-white shadow-lg`}><Icon size={27}/></span><span className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">{service.eyebrow}</span></div><h3 className="mt-8 text-2xl font-bold text-[#071B3B]">{service.title}</h3><p className="mt-4 min-h-[78px] text-[15px] leading-7 text-slate-600">{service.description}</p><button onClick={() => navigate("/services")} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-blue-50 px-4 py-3 text-sm font-bold text-[#1559bd] transition hover:bg-[#1559bd] hover:text-white">Explore capability <ArrowRight size={17} className="transition group-hover:translate-x-1"/></button></article>; })}</div></div></section>;
}
