import { Navigate, useParams } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import SEO from "../components/SEO";
import { articleBySlug, publishedArticles } from "../data/blog";
import { allServices } from "../data/services";
import { Breadcrumbs, CTA, SectionHeader, ServiceCard } from "../components/services/ServiceUI";

export default function ArticleDetail() {
  const { slug } = useParams(); const article = articleBySlug[slug];
  if (!article) return <Navigate to="/blog" replace />;
  const services = allServices.filter((service) => article.services.includes(service.slug));
  const related = publishedArticles.filter((item) => item.slug !== article.slug && (item.category === article.category || item.tags.some((tag) => article.tags.includes(tag)))).slice(0, 3);
  return <><SEO title={`${article.title} | ARINSA AI MINDS`} description={article.excerpt} canonical={`/blog/${article.slug}`} /><Navbar/><main><header className="bg-[#071B3B] text-white py-16"><div className="max-w-[980px] mx-auto px-6"><Breadcrumbs items={[{ label: "Home", to: "/" }, { label: "Blog", to: "/blog" }, { label: article.category }, { label: article.title }]} /><p className="text-blue-200 uppercase font-bold text-sm tracking-[.16em] mt-10">{article.category.replaceAll("-", " ")}</p><h1 className="text-4xl md:text-6xl font-bold leading-tight mt-4">{article.title}</h1><p className="text-xl text-blue-50/90 leading-8 mt-6">{article.excerpt}</p><p className="text-blue-200 mt-6">{article.author} · {article.readingTime} min read · Draft editorial content pending technical review</p></div></header><div className="max-w-[1180px] mx-auto px-6 py-16 grid lg:grid-cols-[210px_1fr] gap-14"><aside className="lg:sticky lg:top-32 h-fit"><p className="font-bold">On this page</p><ol className="mt-4 space-y-3 text-sm text-slate-600">{article.body.map((_, index) => <li key={index}><a href={`#section-${index + 1}`}>Section {index + 1}</a></li>)}</ol></aside><article className="max-w-[760px]"><img src={article.image} alt={`${article.title} editorial visual`} className="w-full aspect-[16/8] object-cover rounded-2xl" /><div className="bg-blue-50 border border-blue-100 rounded-2xl p-6 mt-8"><h2 className="font-bold text-xl">Key takeaways</h2><ul className="mt-3 list-disc pl-5 text-slate-700 space-y-2">{article.body.slice(0, 3).map((paragraph) => <li key={paragraph}>{paragraph.split(". ")[0]}.</li>)}</ul></div>{article.body.map((paragraph, index) => <section id={`section-${index + 1}`} key={paragraph} className="mt-12"><h2 className="text-3xl font-bold">{["Define the problem", "Design the operating workflow", "Build with controls", "Validate and improve"][index] || "Practical considerations"}</h2><p className="text-lg leading-8 text-slate-700 mt-5">{paragraph}</p></section>)}<section className="mt-14 border-t pt-10"><h2 className="text-2xl font-bold">Related services</h2><div className="grid md:grid-cols-2 gap-4 mt-6">{services.map((service) => <ServiceCard key={service.slug} service={service} />)}</div></section></article></div><section className="bg-[#f6f9ff] py-16"><div className="max-w-[1180px] mx-auto px-6"><SectionHeader eyebrow="Keep reading" title="Related insights" /><div className="grid md:grid-cols-3 gap-5 mt-8">{related.map((item) => <a href={`/blog/${item.slug}`} key={item.slug} className="bg-white border rounded-2xl p-6"><p className="text-sm text-[#1559bd] font-bold">{item.category}</p><h3 className="font-bold text-xl mt-3">{item.title}</h3><p className="text-slate-600 mt-3">{item.readingTime} min read</p></a>)}</div></div></section><CTA title="Turn an idea into a working AI or software product." /></main><Footer/></>;
}
