import { useState } from "react";
import { Link, Navigate, useParams } from "react-router-dom";
import { ArrowRight, BookOpen, BriefcaseBusiness, CircleDollarSign, Code2, CloudUpload, Info, Rocket, Sparkles, Trophy } from "lucide-react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import SEO from "../components/SEO";
import internshipHero from "../assets/internship-hero-v2.png";
import { faq, plans } from "../data/internship";
import { Breadcrumbs, CTA, FAQ, SectionHeader } from "../components/services/ServiceUI";

const notice = <div className="border border-blue-200 bg-[#f3f7ff] rounded-xl p-5 text-[#071B3B] flex gap-4"><Info className="text-[#1559bd] shrink-0" size={29}/><div><p className="font-bold">Important program notice</p><p className="mt-1.5 text-sm leading-6">This is a self-paced internship program. There are no live classes and no dedicated mentorship. Participants learn through structured content, coding assignments, assessments and project work.</p><p className="mt-2 text-sm leading-6">Certificates are awarded only after successful completion. Premium priority interview opportunities are merit-based and not guaranteed.</p></div></div>;
const pricing = <div className="border border-amber-200 bg-[#fffaf0] rounded-xl p-5 text-[#071B3B] flex gap-4"><CircleDollarSign className="text-amber-500 shrink-0" size={29}/><div><p className="font-bold">Pricing and payment note</p><ul className="mt-2 space-y-1.5 text-sm leading-6 text-slate-700 list-disc pl-4"><li>GST is applicable to Indian participants as per prevailing Indian tax regulations.</li><li>International participants are charged in USD.</li><li>Payment gateway or currency-conversion charges may be determined by the participant’s bank or payment provider.</li><li>Registration is confirmed only after successful payment verification.</li></ul></div></div>;

const stages = [
  { name: "Learn", text: "Self-paced learning and real-world concepts", icon: BookOpen, tone: "from-[#123f91] to-[#092756] border-blue-400/60" },
  { name: "Build", text: "Work on hands-on projects and assignments", icon: Code2, tone: "from-[#4a277c] to-[#20164b] border-violet-400/70" },
  { name: "Submit", text: "Submit your work and get evaluated", icon: CloudUpload, tone: "from-[#076476] to-[#06344d] border-cyan-400/70" },
  { name: "Evaluate", text: "Receive feedback and improve your skills", icon: Trophy, tone: "from-[#8d4127] to-[#372042] border-orange-400/70" },
];

export function InternshipHome() {
  return <><SEO title="Industry Internship Program | ARINSA AI MINDS" description="A self-paced, project-based internship experience for practical software and AI development skills." canonical="/internship"/><Navbar/><main>
    <section className="relative overflow-hidden bg-[#031534] text-white">
      <div className="absolute inset-0 opacity-70 [background-image:radial-gradient(circle_at_78%_20%,rgba(37,99,235,.45),transparent_25%),radial-gradient(circle_at_4%_90%,rgba(80,73,255,.4),transparent_30%),linear-gradient(125deg,transparent_70%,rgba(0,122,255,.17))]"/>
      <div className="absolute -left-40 bottom-[-11rem] h-96 w-[52rem] rounded-[100%] border border-blue-400/25 blur-[1px]"/>
      <div className="relative max-w-[1320px] mx-auto px-6 py-14 lg:py-[52px] grid lg:grid-cols-[300px_minmax(340px,430px)_minmax(410px,1fr)] xl:grid-cols-[340px_420px_1fr] gap-7 xl:gap-10 items-center">
        <div className="hidden lg:block self-end -ml-10 xl:-ml-16"><img src={internshipHero} alt="Laptop displaying code for internship project work" className="w-[390px] xl:w-[455px] max-w-none mix-blend-screen [mask-image:radial-gradient(ellipse_at_35%_100%,black_28%,transparent_72%)]"/></div>
        <div className="relative">
          <p className="text-[#65a7ff] uppercase tracking-[.17em] text-[11px] md:text-xs font-bold">ARINSA AI MINDS INDUSTRY INTERNSHIP PROGRAM™</p>
          <h1 className="max-w-[630px] text-4xl md:text-5xl xl:text-[3.45rem] leading-[1.08] font-bold mt-4">Build practical technology skills through structured project work.</h1>
          <p className="max-w-[620px] text-base md:text-[17px] leading-7 text-blue-100/90 mt-5">Develop software and AI development experience through self-paced learning content, coding assignments, assessments and project-based work.</p>
          <div className="flex gap-4 flex-wrap mt-7"><Link to="/internship/register" className="bg-[#1954e8] hover:bg-[#2b64f0] px-5 py-3 rounded-lg font-bold text-sm flex items-center gap-3 shadow-lg shadow-blue-950/30">Register for internship <ArrowRight size={17}/></Link><a href="#plans" className="border border-white/65 hover:bg-white/10 px-5 py-3 rounded-lg font-bold text-sm">Compare programs</a></div>
        </div>
        <div className="grid grid-cols-2 gap-4 max-w-[520px] justify-self-center lg:justify-self-end w-full">{stages.map(({ name, text, icon: Icon, tone }) => <article key={name} className={`min-h-[180px] md:min-h-[198px] rounded-2xl border bg-gradient-to-br ${tone} p-5 md:p-6 flex flex-col shadow-[inset_0_1px_0_rgba(255,255,255,.15),0_15px_45px_rgba(0,0,0,.2)]`}><Icon size={54} strokeWidth={1.35} className="text-blue-100 drop-shadow-[0_0_16px_rgba(73,159,255,.8)]"/><h2 className="font-bold text-lg mt-auto">{name}</h2><p className="text-blue-50/90 text-sm leading-5 mt-1 max-w-[160px]">{text}</p><span className="self-end -mt-6 border border-white/60 rounded-full p-1.5"><ArrowRight size={15}/></span></article>)}</div>
      </div>
    </section>
    <section className="py-6 md:py-7 bg-white"><div className="max-w-[900px] xl:max-w-[920px] mx-auto px-6 grid lg:grid-cols-2 gap-5">{notice}{pricing}</div></section>
        <section id="plans" className="relative py-16 md:py-20 overflow-hidden bg-[linear-gradient(120deg,#f4f8ff,#fff)]"><div className="absolute right-[10%] top-10 text-blue-100"><Code2 size={185} strokeWidth={.65}/></div><div className="relative max-w-[1320px] mx-auto px-6"><SectionHeader eyebrow="Choose a program" title="Plans designed for different levels of project experience."/><div className="grid lg:grid-cols-3 gap-6 mt-10">{plans.map((plan, index) => <article key={plan.slug} className={`bg-white border-2 ${plan.accent} rounded-2xl p-7 ${plan.highlighted ? "shadow-xl shadow-blue-950/10" : ""}`}><div className="flex items-center gap-3"><span className={`p-2 rounded-lg ${index === 0 ? "bg-orange-50 text-orange-500" : index === 1 ? "bg-blue-50 text-blue-700" : "bg-violet-50 text-violet-700"}`}>{index === 0 ? <Rocket size={22}/> : index === 1 ? <BriefcaseBusiness size={22}/> : <Sparkles size={22}/>}</span><p className="font-bold text-[#1559bd]">{plan.name}</p></div><h2 className="text-2xl font-bold mt-5">{plan.price}</h2><p className="text-[#1559bd] font-semibold mt-1">International: {plan.internationalPrice}</p><p className="text-slate-600 mt-2">{plan.duration}</p><p className="text-slate-600 leading-7 mt-5">{plan.description}</p><ul className="mt-6 space-y-3 text-slate-700">{plan.features.map(x => <li key={x} className="flex gap-2"><span className="text-[#1559bd]">•</span>{x}</li>)}</ul><Link to={`/internship/register?plan=${plan.slug}`} className="block text-center bg-[#1559bd] hover:bg-[#0e479f] text-white rounded-xl py-3.5 font-bold mt-8">Choose {plan.name.replace(" Internship", "")}</Link></article>)}</div></div></section>
    <section className="py-20"><div className="max-w-[1320px] mx-auto px-6"><SectionHeader eyebrow="Technologies and skills" title="Coverage depends on your selected program and assigned track." body="Participation does not guarantee mastery of every listed technology."/><div className="grid md:grid-cols-5 gap-4 mt-10">{[["Programming & Backend","Python, FastAPI, REST APIs"],["Frontend","React.js, Next.js, TypeScript"],["Databases","SQL"],["Workflow","Git, GitHub, documentation, code submission"],["AI","AI applications, LLMs, prompt engineering, API integration"]].map(([a,b]) => <div key={a} className="border rounded-xl p-5"><h3 className="font-bold">{a}</h3><p className="text-slate-600 text-sm leading-6 mt-3">{b}</p></div>)}</div></div></section>
    <section className="py-20 bg-[#071B3B] text-white"><div className="max-w-[1320px] mx-auto px-6"><SectionHeader light eyebrow="Registration and completion journey" title="Clear stages, recorded status."/><div className="grid md:grid-cols-4 lg:grid-cols-7 gap-3 mt-10">{["Register","Access portal","Complete assignments","Submit projects","Final assessment","Eligible certificates","Premium interview eligibility"].map((x,i) => <div key={x} className="border border-white/15 rounded-xl p-4"><span className="text-blue-200 font-bold">0{i+1}</span><p className="font-semibold mt-5">{x}</p></div>)}</div></div></section>
    <section className="py-20"><div className="max-w-[900px] mx-auto px-6"><SectionHeader eyebrow="Internship FAQ" title="Important program information."/><FAQ items={faq}/><Link to="/internship/faq" className="inline-block mt-8 text-[#1559bd] font-bold">View all program FAQs →</Link></div></section><CTA title="Start your practical project journey." body="Review the program requirements and choose the plan that fits your current development goals."/>
  </main><Footer/></>;
}

export function InternshipPlan(){const {planSlug}=useParams();const plan=plans.find(x=>x.slug===planSlug);if(!plan)return <Navigate to="/internship" replace/>;return <><SEO title={`${plan.name} | ARINSA AI MINDS`} description={plan.description} canonical={`/internship/${plan.slug}`}/><Navbar/><main><section className="bg-[#071B3B] text-white py-16"><div className="max-w-[1000px] mx-auto px-6"><Breadcrumbs items={[{label:"Home",to:"/"},{label:"Internship",to:"/internship"},{label:plan.name}]}/><h1 className="text-5xl font-bold mt-10">{plan.name}</h1><p className="text-xl text-blue-50 mt-5">{plan.description}</p><p className="text-3xl font-bold mt-8">Indian participants: {plan.price}</p><p className="text-xl text-blue-100 mt-2">International participants: {plan.internationalPrice} · {plan.duration}</p></div></section><section className="py-16"><div className="max-w-[1000px] mx-auto px-6 grid gap-6">{notice}{pricing}<h2 className="text-3xl font-bold mt-6">What is included</h2><ul className="space-y-4">{plan.features.map(x=><li key={x} className="border rounded-xl p-5">{x}</li>)}</ul><Link to={`/internship/register?plan=${plan.slug}`} className="inline-block w-fit bg-[#1559bd] text-white px-6 py-3.5 rounded-xl font-bold">Register for {plan.name}</Link></div></section></main><Footer/></>}
export function InternshipRegister(){const [submitted,setSubmitted]=useState(false);return <><SEO title="Register for Internship | ARINSA AI MINDS" description="Internship registration interface." canonical="/internship/register"/><Navbar/><main className="bg-[#f6f9ff] py-16"><div className="max-w-[760px] mx-auto px-6"><h1 className="text-4xl font-bold">Internship registration</h1><p className="text-slate-600 mt-4">Registration and payment require a secure backend before enrollment can be activated.</p><div className="mt-6">{pricing}</div>{submitted?<div className="mt-8 bg-amber-50 border border-amber-200 rounded-2xl p-6">Your information has not been submitted because registration integration is not configured yet. Please contact ARINSA AI MINDS for the approved registration process.</div>:<form onSubmit={e=>{e.preventDefault();setSubmitted(true)}} className="bg-white border rounded-2xl p-7 mt-8 grid gap-5"><label>Full name<input required className="mt-2 w-full border rounded-xl p-3"/></label><label>Email address<input required type="email" className="mt-2 w-full border rounded-xl p-3"/></label><label>Preferred program<select className="mt-2 w-full border rounded-xl p-3">{plans.map(x=><option key={x.slug}>{x.name}</option>)}</select></label><label className="flex gap-3"><input type="checkbox" required/>I understand this is self-paced, has no live classes or dedicated mentorship, and certificates require successful completion.</label><label className="flex gap-3"><input type="checkbox" required/>I agree to the program terms.</label><button className="bg-[#1559bd] text-white rounded-xl py-3.5 font-bold">Continue when registration is available</button></form>}</div></main><Footer/></>}
export function InternshipFAQ(){return <><SEO title="Internship FAQ | ARINSA AI MINDS" description="Frequently asked questions about the ARINSA AI MINDS internship program." canonical="/internship/faq"/><Navbar/><main className="py-16"><div className="max-w-[900px] mx-auto px-6"><h1 className="text-4xl font-bold">Internship FAQ</h1><FAQ items={faq}/></div></main><Footer/></>}
